export { default as DashboardPage } from './Dashboard';
export { default as ProductPage } from './Product';
export { default as ImportsPage } from './Imports';
export { default as EmployeePage } from './Employee';
export { default as TransactionPage } from './Transaction';
export { default as PricePage } from './Price';
export { default as SettingPage } from './Setting';
export { default as StockTakePage } from './StockTake';
export { default as SupplierPage } from './Supplier';
